// GLOBAL TYPES
export const SET_ERROR = 'SET_ERROR';
export const CHANGE_ACTIVE_SPRINT = 'CHANGE_ACTIVE_SPRINT';
export const SET_SPRINTS = 'SET_SPRINTS';
export const SET_UPDATING_STATUS = 'SET_UPDATING_STATUS';

// PROJECTS
export const SET_FIRST_PAGE_INFO = 'SET_FIRST_PAGE_INFO';
export const SET_RELEASES_INFO = 'SET_RELEASES_INFO';
export const SET_CHOOSED_RELEASE = 'SET_CHOOSED_RELEASE';
export const SET_CHOOSED_CYCLE = 'SET_CHOOSED_CYCLE';
export const SET_PROJECT_FETCHING = 'SET_PROJECT_FETCHING';
export const SET_CYCLES = 'SET_CYCLES';
export const SET_RELEASE_FETCHING = 'SET_RELEASE_FETCHING';
export const SET_CYCLE_TYPES = 'SET_CYCLE_TYPES';
export const SET_TEAMS_FETCHING = 'SET_TEAMS_FETCHING';
export const SET_TEAMS = 'SET_TEAMS';
export const SET_ALL_TEAMS_FETCHING = 'SET_ALL_TEAMS_FETCHING';
export const SET_PROJECT_SPRINT_STAT = 'SET_PROJECT_SPRINT_STAT';
export const SET_SHOW_SPRINT_INFO = 'SET_SHOW_SPRINT_INFO';
export const SET_TEAMS_CYCLE_STATS = 'SET_TEAMS_CYCLE_STATS';

// PAGES
export const CHANGE_ACTIVE_LINK = 'CHANGE_ACTIVE_LINK';

// TESTS
export const SET_TESTS = 'SET_TESTS';
export const SET_FETCHING = 'SET_FETCHING';
export const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';

// BUILDS
export const SET_BUILDS = 'SET_BUILDS';
export const SET_BUILDS_TESTS = 'SET_BUILDS_TESTS';
export const SET_FETCHING_BUILDS = 'SET_FETCHING_BUILDS';
export const SET_FIRST_SELECT = 'SET_FIRST_SELECT';
export const SET_SECOND_SELECT = 'SET_SECOND_SELECT';
export const SET_SUCCESS_FILTER = 'SET_SUCCESS_FILTER';
export const SET_FAILED_FILTER = 'SET_FAILED_FILTER';
export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';
export const SET_PULL_REQUESTS = 'SET_PULL_REQUESTS';
export const SET_PR_FILTER = 'SET_PR_FILTER';
export const SET_RELEASES = 'SET_RELEASES';
export const SET_KEY_SORT = 'SET_KEY_SORT';
export const CLEAR_BUILDS_FILTER = 'CLEAR_BUILDS_FILTER';
